export const ROUTES = {
  Home: '/',
  Browser: '/',
  Neighborhoods: '/',
  Entrepreneurship: '/entreprenure',
  WhoWeAre: '/',
  Services: '/',
  Login: '/login',
  Appraisals: '/tasaciones',
  Contact: '/contacto',
  Construction: '/construction',
  // Protected Routes
  homeAgent: '/tab-agent',
  newLocality: '/tab-agent/new-location',
  locationList: '/tab-agent/location-list',
  newNeighborhood: '/tab-agent/new-neighborhood',
  neighborhoodList: '/tab-agent/neighborhood-list',
  newEntrepreneurship: '/tab-agent/new-entrepreneurship',
  entrepreneurshipList: '/tab-agent/entrepreneurship-list',
  newProperty: '/tab-agent/new-property',
  propertyList: '/tab-agent/property-list',
  agentProfile: '/tab-agent/profile',
  //Client Routes
  clientHome: "/tab-client",
  clientFavorites: "/tab-client/favorites",
  clientSearchs: "/tab-client/search",
  clientComparisons: "/tab-client/comparisons",
  clientRequests: "/tab-client",
  // Admin Routes 
  adminHome: '/tab-admin',
  formWhoWeAre: '/tab-admin/form-whoweare',
  formHome: '/tab-admin/form-home',
  newAgent: '/tab-admin/new-agent',
  tabClient: '/tab-client'
}
