export const ROUTES = {
  Home: '/start',
  Browser: '/search-map',
  Neighborhoods: '/search-map',
  Entrepreneurship: '/entreprenureship',
  WhoWeAre: '/aboutus',
  Services: '/construction',
  Login: '/login',
  Appraisals: '/tasaciones',
  Contact: '/contacto',
  Construction: '/construction',
  // Protected Routes
  homeAgent: '/tab-agent',
  newLocality: '/tab-agent/new-location',
  locationList: '/tab-agent/location-list',
  newNeighborhood: '/tab-agent/new-neighborhood',
  neighborhoodList: '/tab-agent/neighborhood-list',
  newEntrepreneurship: '/tab-agent/new-entrepreneurship',
  entrepreneurshipList: '/tab-agent/entrepreneurship-list',
  newProperty: '/tab-agent/new-property',
  propertyList: '/tab-agent/property-list',
  agentProfile: '/tab-agent/profile',
  //Client Routes
  clientHome: "/tab-client",
  clientFavorites: "/tab-client/favorites",
  clientSearchs: "/tab-client/search",
  clientComparisons: "/tab-client/comparisons",
  clientRequests: "/tab-client",
  clientProfile: "/tab-client",
  // Admin Routes 
  adminHome: '/tab-admin',
  formWhoWeAre: '/tab-admin/form-whoweare',
  formHome: '/tab-admin/form-home',
  formServices: '/tab-admin',
  formAppraisals: '/tab-admin',
  newAgent: '/tab-admin/new-agent',
  newClient: '/tab-admin',
  tabClient: '/tab-admin',
  adminProfile: "/tab-admin",
}
